language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: Ig7tpcYg7ptCNsaAC/jJ0nJ2EwlcPOV8PLC1jc8abQN+StxLRfCoFh8mAFwIRPt7ZzO3JXD5pYia/kZl4B964cI9xTWqiPIJKC4DQFYiLu0vtq8jsj1epX4IZ50HxdvMmWFOcFEU2VJc5B1AvK4ad931NitC62ETiRrMKHlzcAEs66CH8Xgl0rTMYKIvT2ZcGLIe8KkGctvJqhHt/DsUTZ9Sw5yJrsb7BtSAQPntN9/syu7ST9C2fqN2RBszHIqsRiFTMgeDUzZ6zIpRYvaZvAeZI2YnxDeNrkkkpdbYbM4nHx/jhqjWRXzgG7l98f2ydFRsdKwbeTSZlgPHXkXZAf28y7DqPdz9wtdgNta27yhXqgzgM3Sztg1PQx8y7mFJWxcHMRrDUoyPuGFBeIeltcWocc7OCR19eboIqhNNUiD3a5k5BeNPu4C36WjRPs0VqvE55biFecpENPlc2DbVo4p7bQdZb3dY/JK93bxwS6cePOfz6mIp/Ir5TCF6ELUeab5U2D80fWzXJsenhTdVna11ragCgWve9cn/+C6WUNPvAkDXsDXCJ5aUJzxlO1oejV3y1zQzSDG/S3usqLPeHCeNpE+lhtR6JPAmUMGnVaK0WgdIw+rXcDcPgnOi92zBDzSx7LMQ7BrVUV8RAlB07V+ZeRBsk8UQoS5urmlRbOg=
    on:
      branch: master
      tags: true